export const places = ["School",
    "Hospital",
    "Library",
    "Grocery Store",
    "Park",
    "Museum",
    "Fire Station",
    "Police Station",
    "Post Office",
    "Bank",
    "Restaurant",
    "Cafe",
    "Bar",
    "Hotel",
    "Gym",
    "Pharmacy",
    "Shopping Mall",
    "Movie Theater",
    "Playground",
    "Church",
    "Synagogue",
    "Mosque",
    "Temple",
    "University",
    "College",
    "High School",
    "Middle School",
    "Elementary School",
    "Kindergarten",
    "Daycare Center",
    "Nursing Home",
    "Community Center",
    "Zoo",
    "Aquarium",
    "Stadium",
    "Sports Complex",
    "Golf Course",
    "Tennis Court",
    "Basketball Court",
    "Soccer Field",
    "Baseball Field",
    "Swimming Pool",
    "Skate Park",
    "Amusement Park",
    "Water Park",
    "Convention Center",
    "Exhibition Hall",
    "Concert Hall",
    "Opera House",
    "Art Gallery",
    "Science Center",
    "Planetarium",
    "Observatory",
    "Train Station",
    "Bus Station",
    "Airport",
    "Harbor",
    "Dock",
    "Warehouse",
    "Factory",
    "Office Building",
    "Government Building",
    "Courthouse",
    "Jail",
    "Prison",
    "Cemetery",
    "Funeral Home",
    "Crematorium",
    "Gas Station",
    "Car Wash",
    "Auto Repair Shop",
    "Parking Garage",
    "Parking Lot",
    "Veterinary Clinic",
    "Animal Shelter",
    "Pet Store",
    "Hardware Store",
    "Bookstore",
    "Clothing Store",
    "Electronics Store",
    "Furniture Store",
    "Toy Store",
    "Supermarket",
    "Bakery",
    "Butcher Shop",
    "Fish Market",
    "Farmers Market",
    "Flower Shop",
    "Garden Center",
    "Laundromat",
    "Dry Cleaner",
    "Barber Shop",
    "Hair Salon",
    "Nail Salon",
    "Spa",
    "Tattoo Parlor",
    "Dentist Office",
    "Chiropractor Office",
    "Optometrist Office",
    "Orthodontist Office",
    "Psychiatrist Office",
    "Therapist Office",
    "Rehabilitation Center",
    "Emergency Room"
]
